//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Kernels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kernels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSharp.Resources.Kernels", typeof(Kernels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolate.
        /// </summary>
        public static string BorderTypeIsolated {
            get {
                return ResourceManager.GetString("BorderTypeIsolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflect.
        /// </summary>
        public static string BorderTypeReflect {
            get {
                return ResourceManager.GetString("BorderTypeReflect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflect101.
        /// </summary>
        public static string BorderTypeReflect101 {
            get {
                return ResourceManager.GetString("BorderTypeReflect101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate.
        /// </summary>
        public static string BorderTypeReplicate {
            get {
                return ResourceManager.GetString("BorderTypeReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap.
        /// </summary>
        public static string BorderTypeWrap {
            get {
                return ResourceManager.GetString("BorderTypeWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Blur.
        /// </summary>
        public static string BoxBlur {
            get {
                return ResourceManager.GetString("BoxBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canny.
        /// </summary>
        public static string Canny {
            get {
                return ResourceManager.GetString("Canny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directional Edge Detection.
        /// </summary>
        public static string DirectionalEdgeDetection {
            get {
                return ResourceManager.GetString("DirectionalEdgeDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Detection.
        /// </summary>
        public static string EdgeDetection {
            get {
                return ResourceManager.GetString("EdgeDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Blur.
        /// </summary>
        public static string GaussianBlur {
            get {
                return ResourceManager.GetString("GaussianBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laplacian.
        /// </summary>
        public static string Laplacian {
            get {
                return ResourceManager.GetString("Laplacian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prewitt.
        /// </summary>
        public static string Prewitt {
            get {
                return ResourceManager.GetString("Prewitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string PrewittE {
            get {
                return ResourceManager.GetString("PrewittE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string PrewittN {
            get {
                return ResourceManager.GetString("PrewittN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string PrewittNE {
            get {
                return ResourceManager.GetString("PrewittNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string PrewittNW {
            get {
                return ResourceManager.GetString("PrewittNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string PrewittS {
            get {
                return ResourceManager.GetString("PrewittS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string PrewittSE {
            get {
                return ResourceManager.GetString("PrewittSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string PrewittSW {
            get {
                return ResourceManager.GetString("PrewittSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string PrewittW {
            get {
                return ResourceManager.GetString("PrewittW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        public static string Sharpen {
            get {
                return ResourceManager.GetString("Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Mask 1.
        /// </summary>
        public static string SharpenMask1 {
            get {
                return ResourceManager.GetString("SharpenMask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Mask 2.
        /// </summary>
        public static string SharpenMask2 {
            get {
                return ResourceManager.GetString("SharpenMask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Mask 3.
        /// </summary>
        public static string SharpenMask3 {
            get {
                return ResourceManager.GetString("SharpenMask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothe.
        /// </summary>
        public static string Smoothe {
            get {
                return ResourceManager.GetString("Smoothe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobel.
        /// </summary>
        public static string Sobel {
            get {
                return ResourceManager.GetString("Sobel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Sobel.
        /// </summary>
        public static string SobelEW {
            get {
                return ResourceManager.GetString("SobelEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Sobel.
        /// </summary>
        public static string SobelNS {
            get {
                return ResourceManager.GetString("SobelNS", resourceCulture);
            }
        }
    }
}
