//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Project {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSharp.Resources.Project", typeof(Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectStr {
            get {
                return ResourceManager.GetString("ProjectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse.
        /// </summary>
        public static string ThresholdingInverse {
            get {
                return ResourceManager.GetString("ThresholdingInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negated.
        /// </summary>
        public static string ThresholdingNegated {
            get {
                return ResourceManager.GetString("ThresholdingNegated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserving Grayscale Levels.
        /// </summary>
        public static string ThresholdingPreservingGrayscaleLevels {
            get {
                return ResourceManager.GetString("ThresholdingPreservingGrayscaleLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserving Grayscale Levels (Negation).
        /// </summary>
        public static string ThresholdingPreservingGrayscaleLevelsNegation {
            get {
                return ResourceManager.GetString("ThresholdingPreservingGrayscaleLevelsNegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ThresholdingStandard {
            get {
                return ResourceManager.GetString("ThresholdingStandard", resourceCulture);
            }
        }
    }
}
