//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolve.
        /// </summary>
        public static string Convolve {
            get {
                return ResourceManager.GetString("Convolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilate.
        /// </summary>
        public static string Dilate {
            get {
                return ResourceManager.GetString("Dilate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double- and Single Convolve.
        /// </summary>
        public static string DoubleConvolve {
            get {
                return ResourceManager.GetString("DoubleConvolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Detection (Hough).
        /// </summary>
        public static string EdgeDetection_Hough {
            get {
                return ResourceManager.GetString("EdgeDetection_Hough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalize Histogram.
        /// </summary>
        public static string EqualizeHistogram {
            get {
                return ResourceManager.GetString("EqualizeHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erode.
        /// </summary>
        public static string Erode {
            get {
                return ResourceManager.GetString("Erode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrabCut.
        /// </summary>
        public static string GrabCut {
            get {
                return ResourceManager.GetString("GrabCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB to Grayscale.
        /// </summary>
        public static string Grayize {
            get {
                return ResourceManager.GetString("Grayize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string Histogram {
            get {
                return ResourceManager.GetString("Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Processing Program.
        /// </summary>
        public static string Image_Processing_Program {
            get {
                return ResourceManager.GetString("Image Processing Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Calculator.
        /// </summary>
        public static string ImageCalculator {
            get {
                return ResourceManager.GetString("ImageCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpaint.
        /// </summary>
        public static string Inpaint {
            get {
                return ResourceManager.GetString("Inpaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel/Mask Size.
        /// </summary>
        public static string KernelMaskSize {
            get {
                return ResourceManager.GetString("KernelMaskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphological Closing.
        /// </summary>
        public static string MorphologicalClose {
            get {
                return ResourceManager.GetString("MorphologicalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphological Opening.
        /// </summary>
        public static string MorphologicalOpen {
            get {
                return ResourceManager.GetString("MorphologicalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphological Operations.
        /// </summary>
        public static string MorphologicalOperations {
            get {
                return ResourceManager.GetString("MorphologicalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negate.
        /// </summary>
        public static string Negate {
            get {
                return ResourceManager.GetString("Negate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Grayscale.
        /// </summary>
        public static string OpenGray {
            get {
                return ResourceManager.GetString("OpenGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open RGB.
        /// </summary>
        public static string OpenRGB {
            get {
                return ResourceManager.GetString("OpenRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string PixelIntensity {
            get {
                return ResourceManager.GetString("PixelIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Profile.
        /// </summary>
        public static string PlotProfile {
            get {
                return ResourceManager.GetString("PlotProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterize.
        /// </summary>
        public static string Posterize {
            get {
                return ResourceManager.GetString("Posterize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Down.
        /// </summary>
        public static string PyramidDown {
            get {
                return ResourceManager.GetString("PyramidDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Up.
        /// </summary>
        public static string PyramidUp {
            get {
                return ResourceManager.GetString("PyramidUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB to HSV.
        /// </summary>
        public static string RgbToHsv {
            get {
                return ResourceManager.GetString("RgbToHsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB to LAB.
        /// </summary>
        public static string RgbToLab {
            get {
                return ResourceManager.GetString("RgbToLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhombus.
        /// </summary>
        public static string Rhombus {
            get {
                return ResourceManager.GetString("Rhombus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Histogram.
        /// </summary>
        public static string ShowHistogram {
            get {
                return ResourceManager.GetString("ShowHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeletonize.
        /// </summary>
        public static string Skeletonize {
            get {
                return ResourceManager.GetString("Skeletonize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Channels.
        /// </summary>
        public static string SplitChannels {
            get {
                return ResourceManager.GetString("SplitChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Contrast.
        /// </summary>
        public static string StretchContrast {
            get {
                return ResourceManager.GetString("StretchContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Histogram.
        /// </summary>
        public static string StretchHistogram {
            get {
                return ResourceManager.GetString("StretchHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structuring Element.
        /// </summary>
        public static string StructuringElement {
            get {
                return ResourceManager.GetString("StructuringElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thresholding.
        /// </summary>
        public static string Thresholding {
            get {
                return ResourceManager.GetString("Thresholding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watershed.
        /// </summary>
        public static string Watershed {
            get {
                return ResourceManager.GetString("Watershed", resourceCulture);
            }
        }
    }
}
