//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is already grayscale.
        /// </summary>
        public static string AlreadyGrayscale_Error {
            get {
                return ResourceManager.GetString("AlreadyGrayscale_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Window.
        /// </summary>
        public static string ChbNewWindow {
            get {
                return ResourceManager.GetString("ChbNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose number of posterization levels.
        /// </summary>
        public static string ChoosePosterizationLevelsNumber {
            get {
                return ResourceManager.GetString("ChoosePosterizationLevelsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolve.
        /// </summary>
        public static string Convolve {
            get {
                return ResourceManager.GetString("Convolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dylacja.
        /// </summary>
        public static string Dilate {
            get {
                return ResourceManager.GetString("Dilate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalize Histogram.
        /// </summary>
        public static string EqualizeHistogram {
            get {
                return ResourceManager.GetString("EqualizeHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erode.
        /// </summary>
        public static string Erode {
            get {
                return ResourceManager.GetString("Erode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB to Grayscale.
        /// </summary>
        public static string Grayize {
            get {
                return ResourceManager.GetString("Grayize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram for the image is already open..
        /// </summary>
        public static string HistogramAlreadyOpen {
            get {
                return ResourceManager.GetString("HistogramAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation requires for the histogram of the selected image to be open..
        /// </summary>
        public static string HistogramNotOpen {
            get {
                return ResourceManager.GetString("HistogramNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Processing Program.
        /// </summary>
        public static string Image_Processing_Program {
            get {
                return ResourceManager.GetString("Image Processing Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Calculator.
        /// </summary>
        public static string ImageCalculator {
            get {
                return ResourceManager.GetString("ImageCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected operation may only be performed on color images..
        /// </summary>
        public static string ImageNotColor {
            get {
                return ResourceManager.GetString("ImageNotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected operation may only be performed on grayscale images..
        /// </summary>
        public static string ImageNotGrayscale {
            get {
                return ResourceManager.GetString("ImageNotGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load image..
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphological Closing.
        /// </summary>
        public static string MorphologicalClose {
            get {
                return ResourceManager.GetString("MorphologicalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphological Opening.
        /// </summary>
        public static string MorphologicalOpen {
            get {
                return ResourceManager.GetString("MorphologicalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary Morphological Operations.
        /// </summary>
        public static string MorphologicalOperations {
            get {
                return ResourceManager.GetString("MorphologicalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negate.
        /// </summary>
        public static string Negate {
            get {
                return ResourceManager.GetString("Negate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is focused.
        /// </summary>
        public static string NoImageFocused {
            get {
                return ResourceManager.GetString("NoImageFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is open.
        /// </summary>
        public static string NoImageOpen {
            get {
                return ResourceManager.GetString("NoImageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Grayscale.
        /// </summary>
        public static string OpenGray {
            get {
                return ResourceManager.GetString("OpenGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open RGB.
        /// </summary>
        public static string OpenRGB {
            get {
                return ResourceManager.GetString("OpenRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string PixelIntensity {
            get {
                return ResourceManager.GetString("PixelIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterize.
        /// </summary>
        public static string Posterize {
            get {
                return ResourceManager.GetString("Posterize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB to HSV.
        /// </summary>
        public static string RgbToHsv {
            get {
                return ResourceManager.GetString("RgbToHsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB to LAB.
        /// </summary>
        public static string RgbToLab {
            get {
                return ResourceManager.GetString("RgbToLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhombus.
        /// </summary>
        public static string Rhombus {
            get {
                return ResourceManager.GetString("Rhombus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Histogram.
        /// </summary>
        public static string ShowHistogram {
            get {
                return ResourceManager.GetString("ShowHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Channels.
        /// </summary>
        public static string SplitChannels {
            get {
                return ResourceManager.GetString("SplitChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Contrast.
        /// </summary>
        public static string StretchContrast {
            get {
                return ResourceManager.GetString("StretchContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Histogram.
        /// </summary>
        public static string StretchHistogram {
            get {
                return ResourceManager.GetString("StretchHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 1:.
        /// </summary>
        public static string TextBlockImage1 {
            get {
                return ResourceManager.GetString("TextBlockImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 2:.
        /// </summary>
        public static string TextBlockImage2 {
            get {
                return ResourceManager.GetString("TextBlockImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:.
        /// </summary>
        public static string TextBlockOperation {
            get {
                return ResourceManager.GetString("TextBlockOperation", resourceCulture);
            }
        }
    }
}
