//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSharp.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSharp.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open at least 2 images.
        /// </summary>
        public static string _2ImagesMustBeOpen {
            get {
                return ResourceManager.GetString("_2ImagesMustBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 2 points in image.
        /// </summary>
        public static string _2PointsMustBeSelected {
            get {
                return ResourceManager.GetString("_2PointsMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is already grayscale.
        /// </summary>
        public static string AlreadyGrayscale_Error {
            get {
                return ResourceManager.GetString("AlreadyGrayscale_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram for the image is already open..
        /// </summary>
        public static string HistogramAlreadyOpen {
            get {
                return ResourceManager.GetString("HistogramAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation requires for the histogram of the selected image to be open..
        /// </summary>
        public static string HistogramNotOpen {
            get {
                return ResourceManager.GetString("HistogramNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected operation may only be performed on color images..
        /// </summary>
        public static string ImageNotColor {
            get {
                return ResourceManager.GetString("ImageNotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected operation may only be performed on grayscale images..
        /// </summary>
        public static string ImageNotGrayscale {
            get {
                return ResourceManager.GetString("ImageNotGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images must have the same dimensions..
        /// </summary>
        public static string ImagesMustBeOfSameSize {
            get {
                return ResourceManager.GetString("ImagesMustBeOfSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load image..
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to access the compressed image file..
        /// </summary>
        public static string LoadingFailedRle {
            get {
                return ResourceManager.GetString("LoadingFailedRle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected file is not a valid JSharp compressed image..
        /// </summary>
        public static string InvalidRleFile {
            get {
                return ResourceManager.GetString("InvalidRleFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size must be in the form "min-max"....
        /// </summary>
        public static string InvalidSizeRange {
            get {
                return ResourceManager.GetString("InvalidSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading personalized settings failed.
        ///
        ///Start loading default settings....
        /// </summary>
        public static string LoadingSettingsFailed {
            get {
                return ResourceManager.GetString("LoadingSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image subjected to skeletonization must be a binary image. Posterize the image to 2 grayscale levels or perform thresholding..
        /// </summary>
        public static string MustBeBinary {
            get {
                return ResourceManager.GetString("MustBeBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is focused.
        /// </summary>
        public static string NoImageFocused {
            get {
                return ResourceManager.GetString("NoImageFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is open.
        /// </summary>
        public static string NoImageOpen {
            get {
                return ResourceManager.GetString("NoImageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs a color image. Open a color image, or convert this one to color first..
        /// </summary>
        public static string OperationRequiresColorImage {
            get {
                return ResourceManager.GetString("OperationRequiresColorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs a grayscale image. Convert it first via Image → Grayize..
        /// </summary>
        public static string OperationRequiresGrayscaleImage {
            get {
                return ResourceManager.GetString("OperationRequiresGrayscaleImage", resourceCulture);
            }
        }
    }
}
